### ISSUE TITLE
为什么我的数据是在Y轴下面?（请大神回复下，比较急！！！）

### ISSUE THREAD

**Issue by LyLuu-bug** [SunriseOYR/ORChartView#10]
你好，大神，我想请教一下如下问题。
1、为什么数据在Y轴下面绘制的。
2、数据指示器如何调位置。
3、x轴的间距最大可调控吗？。
<img width="342" alt="image" src="https://user-images.githubusercontent.com/12064268/71867024-6b3dbf00-3143-11ea-961f-f81eb56214e7.png">

**Comment by LyLuu-bug** [comment]
数据偏下的问题我知道为什么了 因为容器不够高。

**Comment by SunriseOYR** [comment]
数据指示器 indicatorContentInset 调位置， x轴间距 用 bottomLabelWidth

**Comment by SunriseOYR** [comment]
数据指示器 的上下位置， 暂时没有提供接口 去调控

**Comment by LyLuu-bug** [comment]
谢谢。 已经解决
