### ISSUE TITLE
最顶部有个ios目标上面 哪里还有一条数据  由于 计算值太小了 非0   导致整个视图有点走形

### ISSUE THREAD

**Issue by LAnqxpp** [SunriseOYR/ORChartView#12]
https://github.com/LAnqxpp/ScreenshotProblemFeedback/blob/master/WechatIMG1530.jpeg

**Comment by LAnqxpp** [comment]
那个右边顶部那个线 应该是 0.05%   没有绘制出来滴色块 好像记录值也无法显示

**Comment by SunriseOYR** [comment]
能把数据 发给我一下，具体数据 ，我好做调试

**Comment by LAnqxpp** [comment]
你能留个联系方式吗

**Comment by LAnqxpp** [comment]
(
        {
        count = 1629;
        createdAt = "2020-01-02 10:39:47";
        sn = 1;
        title = "iOS\U76ee\U6807";
    },
        {
        count = 300;
        createdAt = "2020-01-07 15:48:12";
        sn = 2;
        title = ios12;
    },
        {
        count = 300;
        createdAt = "2020-01-10 16:27:25";
        sn = 9;
        title = "\U5143\U65e6";
    },
        {
        count = 300;
        createdAt = "2020-01-07 15:46:06";
        sn = 8;
        title = "\U4f60\U597d\U5417";
    },
        {
        count = 121;
        createdAt = "2020-01-09 16:12:36";
        sn = 8;
        title = "\U5f00\U59cb\U65f6\U95f4";
    },
        {
        count = 980;
        createdAt = "2020-01-09 15:24:15";
        sn = 6;
        title = "\U901a\U77e5\U751f\U6548";
    },
        {
        count = 480;
        createdAt = "2020-01-07 16:38:53";
        sn = 7;
        title = "\U95ee\U9898";
    },
        {
        count = 120;
        createdAt = "2020-01-14 21:05:46";
        sn = 1;
        title = "\U5173\U4e86";
    },
        {
        count = 420;
        createdAt = "2020-01-13 19:47:46";
        sn = 2;
        title = "\U70b9\U51fb\U95ee\U9898";
    },
        {
        count = 123;
        createdAt = "2020-01-13 19:47:25";
        sn = 6;
        title = "\U7ba1";
    },
        {
        count = 240;
        createdAt = "2020-01-13 14:06:49";
        sn = 5;
        title = push;
    },
        {
        count = 2220;
        createdAt = "2020-01-14 12:12:38";
        sn = 3;
        title = "\U6d4b\U8bd5\U7ed3\U675f";
    }
)

**Comment by SunriseOYR** [comment]
我先看看

**Comment by SunriseOYR** [comment]
我这边看你 数据 只有一个测试结束， 为什么 显示了两个， 感觉是你取数据 出错了。 你检查下

**Comment by SunriseOYR** [comment]
我这边 测试， 没有 出现label 不展示的情况， 除非 你给的是空值

**Comment by SunriseOYR** [comment]
有什么需要QQ 说的吗

**Comment by LAnqxpp** [comment]
QQ 比较及时些  我感觉我在这里面一直和你在盖楼，

**Comment by SunriseOYR** [comment]
1263107985
