### ISSUE TITLE
请问这种效果如何实现呢？

### ISSUE THREAD

**Issue by XiaoXiuXiuYe** [SunriseOYR/ORChartView#14]
![设计图](https://user-images.githubusercontent.com/20794129/77022922-ca327680-69c5-11ea-9a2a-a5bacff0ab4b.png)
![实现效果图](https://user-images.githubusercontent.com/20794129/77024137-b1779000-69c8-11ea-8b01-25a57ca4cba2.png)

因为左右切换的效果，所以我把饼状图和右边的图例放在一个tableViewcell里面，但是饼状图我还是实现不了我想要的这个效果，隐藏了infoLine和point，调了边距，但是toinfoView 无法显示在饼状图圆环的中间，求解。
而且我还发现在我的工程里面明明toinfoView存在，但是不显示，看图层的时候确实存在，我调用 UIView *view =  [self.pieChart dequeueTopInfoViewAtIndex:idx];
view.layer.zPosition = 10;将其显示出来了

**Comment by SunriseOYR** [comment]
你这种情况我最开始确实没有考虑到，如果不着急的话， 我会在这个周末 更新一下

**Comment by SunriseOYR** [comment]
pod已经更新， 需要 update 一下 版本 2.1.8， 具体可以看 github 的示例代码

**Comment by XiaoXiuXiuYe** [comment]
忘记说谢谢了，谢谢哈
