### ISSUE TITLE
问下大佬,咱们库是否能做类似于股票线是的?

### ISSUE THREAD

**Issue by ynpl** [SunriseOYR/ORChartView#17]
类似于这张图, 横坐标 就几个,但是每挪动一下都是一天,坐标轴上只有几个大的标记位!
![iShot2020-05-20上午10 23 42](https://user-images.githubusercontent.com/28553357/82397957-36902b80-9a84-11ea-86ab-a8d4fe6745ea.png)

**Comment by SunriseOYR** [comment]
这个是可以的啊，横坐标你不需要显示的 可以设置空格， 其他的你可能需要改动一下源码

**Comment by ynpl** [comment]
> 这个是可以的啊，横坐标你不需要显示的 可以设置空格， 其他的你可能需要改动一下源码

但现在底下横坐标字的宽度是固定的 如果我设置成每一个宽度是5pt就会上面的折线图看着很好 但是底下的字就会显示...了

**Comment by SunriseOYR** [comment]
源码你改动一下， 底部label的 布局方式就行了

**Comment by ynpl** [comment]
> 源码你改动一下， 底部label的 布局方式就行了

明白啦! 谢谢!
