### ISSUE TITLE
多组数据问题

### ISSUE THREAD

**Issue by sunzeyu157** [SunriseOYR/ORChartView#3]
您好，首先很感谢您的代码，学习了很多，已经 star，我现在想在线形图里接入多组数据，请问您在多线同时显示方面，做了优化了么？

Hello, first of all, thank you very much for your code. I have learned a lot, and now I want to access multiple groups of data in the line graph. Have you optimized the display of multiple lines at the same time?

**Comment by SunriseOYR** [comment]
暂时还没有，后面会考虑，下个月看吧， 最近有点小忙
