### ISSUE TITLE
点击顶点功能问题

### ISSUE THREAD

**Issue by Leeecy** [SunriseOYR/ORChartView#4]
可以在你的demo基础上实现点击顶点上下滑动的效果吗

**Comment by SunriseOYR** [comment]
具体什么意思呢， 点击顶点上下滑动， 不是很懂

**Comment by ma569322307** [comment]
折线图中数组为(
	46,
	100,
	150,
	500,
	200,
	600,
)  只有500和600的时候可以相应  并响应didSelectValueAtIndex方法。其余的点击没反应

**Comment by SunriseOYR** [comment]
好滴，我看下

**Comment by SunriseOYR** [comment]
我刚刚用 ORLineViewController 测试  ORLineChartStyleControl  下  这些数据试没问题的噢， 你看下 视图 可点击区域 是否 正常， 或者还是有其他设置
