### ISSUE TITLE
值很小问题

### ISSUE THREAD

**Issue by simpleLiYu** [SunriseOYR/ORChartView#5]
你好，当我的值都很小的时候有点问题，能看下在哪里能够更改吗
<img width="287" alt="image" src="https://user-images.githubusercontent.com/20043672/64511395-cdfa8780-d316-11e9-8590-1de4b92d62ea.png">

**Comment by SunriseOYR** [comment]
能否把具体的值提供一下， 另外检查一下，你的值是否都相同啊

**Comment by simpleLiYu** [comment]
很多0.1这种小于1的

**Comment by SunriseOYR** [comment]
好滴。这两天会修复的，谢谢指出
