### ISSUE TITLE
关于曲线的【截图】问题

### ISSUE THREAD

**Issue by kakashilw** [SunriseOYR/ORChartView#6]
你好，首先很感谢分享了这么好用的库。

我在使用的时候遇到一个小问题，就是我想把生成的ORLineChartView以图片的形式分享到微信或者qq，然后我用了一个我之前经常用的对UIView截图的方法：

- (UIImage *)convertViewToImage:(UIView *)view {
    
    UIImage *imageRet = [[UIImage alloc] init];
    //UIGraphicsBeginImageContextWithOptions(区域大小, 是否是非透明的, 屏幕密度);
    UIGraphicsBeginImageContextWithOptions(view.frame.size, YES, [UIScreen mainScreen].scale);
    [view.layer renderInContext:UIGraphicsGetCurrentContext()];
    imageRet = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return imageRet;
    
}

发现只能截看到的部分，滚动之后才能看到的部分截取不了，而且曲线上的颜色也没有了。

不知道你这边有什么好的方法吗？

**Comment by SunriseOYR** [comment]
只能截看到的部分 是正常的， 你需要 在截图的时候，把视图 调整到能展示全部的大小，颜色 看不见的问题 我已经修复了， pod 2.0.8， 更新一下

**Comment by kakashilw** [comment]
昨天我也想到了先把frame增大，然后截图完再变回来。。然后颜色这个问题根据你的最新版已经完美解决了，感谢！
