### ISSUE TITLE
关于gradientColors【颜色层次】的问题

### ISSUE THREAD

**Issue by kakashilw** [SunriseOYR/ORChartView#7]
拿默认的两个颜色  self.gradientColors = @[[[UIColor redColor] colorWithAlphaComponent:0.3], [[UIColor blueColor] colorWithAlphaComponent:0.3]]; 举例，如果只是赋值两个颜色，则效果没问题，越在上面红色越深，越在下面蓝色越深，中间是渐变。。

然后我的问题是，我看这个gradientColors可以传递很多值，然后我左边的Y轴，其实是有5个状态，然后我根据这5个状态，传递了5个颜色以后，发现颜色没有像传递2个颜色那样，分成5个层次，而是一个混合在一起的颜色。

所以想请教这个有办法实现传递几个颜色，有几个层次那样的效果吗？类似我在别的app中看到的3个颜色，然后从上往下有3个层次这样。

![xxx](https://user-images.githubusercontent.com/71766/69621272-bca15b80-1079-11ea-8231-8ed94eec8fe6.jpg)

**Comment by SunriseOYR** [comment]
因为 这个 层次 需要 设置 location 参数， 但是 这样和  截图 就 冲突了,  目前 可能 不能 达到 你想要的效果

**Comment by kakashilw** [comment]
> 因为 这个 层次 需要 设置 location 参数， 但是 这样和 截图 就 冲突了, 目前 可能 不能 达到 你想要的效果

你好，最近我又尝试了一下这个颜色分层的效果，还是没有实现如图那种颜色分层的效果，不知可否提供个思路，或者有时间的时候实现一下这个效果呢，我看过挺多app的带颜色曲线都是这种在一个数值区间是一种颜色渐变，然后在另一个区间又是另一种颜色渐变，这样比较能直观的从曲线图看到分布在哪个区间的比较多。

而分享时的截图问题，比起颜色分层来说没有重要，而且我有个思路是分段的屏幕截图，然后再拼接起来，虽然有点麻烦，但是也是可以实现效果。

**Comment by SunriseOYR** [comment]
这边 我新增了 gradientLocations 接口， 你可以通过 调整 这个 参数 去达到你想要的效果，配置 参考CAGradientLayer的 locations 参数
