### ISSUE TITLE
饼图

### ISSUE THREAD

**Issue by leaDongYang** [SunriseOYR/ORChartView#8]
![image](https://user-images.githubusercontent.com/26103383/70370987-2e926400-1908-11ea-8e81-82bffe9abf16.png)
如图，饼图折线会互相遮盖
- (UIView *)viewForRingCenterOfChartView:(ORRingChartView *)chartView{
    UIView *view = [[UIView alloc]initWithFrame:CGRectMake(0, 0, 20, 20)];
    view.backgroundColor = [UIColor grayColor];
    return view;
}
且无法添加中心视图

**Comment by SunriseOYR** [comment]
这边 更新了 中心视图的 显示， 需要更新哈 ， 饼图折线这块 主要是 以文字不遮挡为原则， 暂时没有 更新
