### ISSUE TITLE
 _lineChartView.defaultSelectIndex = 1; 报错

### ISSUE THREAD

**Issue by a381511** [SunriseOYR/ORChartView#9]
当data数组个数为3个时,设置这个参数, 初始x轴 会偏移一大截

**Comment by a381511** [comment]
CGFloat offset = (attr.center.x - attr.frame.size.width / 2.0) * (_collectionView.contentSize.width  + _collectionView.contentInset.left + _collectionView.contentInset.right - _collectionView.bounds.size.width) / (_collectionView.contentSize.width - attr.frame.size.width)- _collectionView.contentInset.left;
     
        [_collectionView setContentOffset:CGPointMake(offset, 0) animated:animated];

**Comment by SunriseOYR** [comment]
感谢指出 已修复，pod 版本 2.1.1

**Comment by a381511** [comment]
这个参数现在貌似失效了,不管设置几 默认都是选中第一个数据

**Comment by SunriseOYR** [comment]
昨天代码传漏了  已修复，pod 版本 2.1.2

**Comment by a381511** [comment]
_indicator value 没有跟着更新  展示的是第一条数据的数值

**Comment by SunriseOYR** [comment]
.... 已更新 再试一哈

**Comment by a381511** [comment]
[_lineChartView reloadData];  刷新数据源  设置index 数据会错乱

**Comment by SunriseOYR** [comment]
能详细 描述哈 操作流程吗

**Comment by SunriseOYR** [comment]
.... 已更新 再试一哈

**Comment by a381511** [comment]
只有一条数据时 , _indicator  会顶到最上方  point 看不到

**Comment by SunriseOYR** [comment]
.... 已更新 再试试
